version: '3.8'
services:
  mysql:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_DATABASE: 'dating_app'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysql", "--help"]
      interval: 10s
      timeout: 5s
      retries: 3
  grpc-server:
    container_name: grpc-server
    build: .
    ports:
      - "9001:9001"
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
    depends_on:
      mysql:
        condition: service_healthy

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    tty: true
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    ports:
      - "8081:80"
# Names our volume
volumes:
  my-db: