# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    - name: ⚙️ Install protoc
      run: |
        sudo apt-get update && sudo apt-get install -y protobuf-compiler
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        mkdir -p "explore"
        protoc --go_out=./explore --go_opt=paths=source_relative \
         --go-grpc_out=./explore --go-grpc_opt=paths=source_relative \
         ./proto/*.proto --experimental_allow_proto3_optional
        go mod download

    - name: Test
      run: go test -v ./pkg/...
